Feat/poetry
tenchi-security/zanshin-sdk-python pull request #93
Opened 2023-02-08 20:31 UTC by Isafagioli-Tenchi

change setup.py to poetry

2023-02-09 17:08 UTC, RomuloGatto requested changes
Faltou também alterar a esteira de release, pra fazer a troca pela versão desejada na hora de release, igual na CLI.

2023-02-09 17:08 UTC, RomuloGatto commented on pyproject.toml
> +version = "1.5.2"
o `setup.py` não tinha versão, então aqui deixa a default 0.1.0

2023-02-09 19:05 UTC, RomuloGatto submitted a review, later dismissed

2023-02-15 17:07 UTC, RomuloGatto approved these changes

2023-02-15 20:26 UTC, edpin approved these changes

2023-02-15 20:26 UTC, edpin commented on pyproject.toml
> +
Do we need so many empty lines?

2023-02-16 14:34 UTC, merged