added pre-commit
tenchi-security/zanshin-sdk-python pull request #94
Opened 2023-02-10 14:48 UTC by Isafagioli-Tenchi

Added pre commit and its changes

2023-02-15 21:12 UTC, asieira requested changes
The entire reason why I asked us to create a CONTRIBUTING.md was to include instructions so developers configure pre-commit hooks on the repo locally in their machines. I didn't see that on the content of the file.

2023-02-16 19:02 UTC, RomuloGatto commented
> The entire reason why I asked us to create a CONTRIBUTING.md was to include instructions so developers configure pre-commit hooks on the repo locally in their machines. I didn't see that on the content of the file.

@asieira to configure locally, it just needs to run the make lint, because it will install all the dependencies automatically, based on the .pre-commit-config.yml, exactly as I wrote on the CONTRIBUTING. Do you have any suggestions for others configurations to be described there?

2023-02-16 20:56 UTC, asieira commented
> > The entire reason why I asked us to create a CONTRIBUTING.md was to include instructions so developers configure pre-commit hooks on the repo locally in their machines. I didn't see that on the content of the file.
> 
> @asieira to configure locally, it just needs to run the make lint, because it will install all the dependencies automatically, based on the .pre-commit-config.yml, exactly as I wrote on the CONTRIBUTING. Do you have any suggestions for others configurations to be described there?

My bad, I read past that make lint comment. Approving the PR, thank you.

2023-02-16 20:56 UTC, asieira approved these changes

2023-02-16 21:05 UTC, merged